BIN				=	asteria-run-coffee.js

all:
	@echo 'Nothing to do for: all'

debug:
	@echo 'Nothing to do for: debug'

install:
	@cp -p $(BIN) /usr/local/bin/asteria-run-coffee
	@chmod +x /usr/local/bin/asteria-run-coffee

clean:
	@echo 'Nothing to do for: clean'
