BIN				=	asteria-repl.js

all:
	@echo 'Nothing to do for: all'

debug:
	@echo 'Nothing to do for: debug'

install:
	@cp -p $(BIN) /usr/local/bin/asteria-repl
	@chmod +x /usr/local/bin/asteria-repl

clean:
	@echo 'Nothing to do for: clean'
